<?php

namespace Fei\Service\Connect\Common\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Fei\Entity\AbstractEntity;

/**
 * Class ProfileAssociation
 *
 * @Entity
 * @Table(name="profiles_association")
 *
 * @package Fei\Service\Connect\Common\Entity
 */
class ProfileAssociation extends AbstractEntity
{
    /**
     * @var int $id
     *
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var User $user
     *
     * @ManyToOne(targetEntity="User", inversedBy="profileAssociations")
     * @JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
     */
    protected $user;

    /**
     * @var Application $application
     *
     * @ManyToOne(targetEntity="Application")
     * @JoinColumn(name="application_id", referencedColumnName="id", nullable=false)
     */
    protected $application;

    /**
     * @var string $role
     *
     * @Column(type="string", length=255)
     */
    protected $role;

    /**
     * @var Profile[] $profile
     * @ManyToMany(targetEntity="Profile", inversedBy="profileAssociations")
     * @JoinTable(name="profileAssociations_profiles")
     */
    protected $profiles;

    public function __construct()
    {
        $this->profiles = new ArrayCollection();
    }

    /**
     * GET Id
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * SET Id
     *
     * @param int $id
     * @return ProfileAssociation
     */
    public function setId(int $id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * GET User
     *
     * @return User
     */
    public function getUser(): User
    {
        return $this->user;
    }

    /**
     * SET User
     *
     * @param User $user
     * @return ProfileAssociation
     */
    public function setUser(User $user): ProfileAssociation
    {
        $this->user = $user;

        return $this;
    }

    /**
     * GET Application
     *
     * @return Application
     */
    public function getApplication(): Application
    {
        return $this->application;
    }

    /**
     * SET Application
     *
     * @param Application $application
     * @return ProfileAssociation
     */
    public function setApplication(Application $application): ProfileAssociation
    {
        $this->application = $application;

        return $this;
    }

    /**
     * Get Role
     *
     * @return string
     */
    public function getRole(): string
    {
        return $this->role;
    }

    /**
     * Set Role
     *
     * @param string $role
     */
    public function setRole(string $role): ProfileAssociation
    {
        $this->role = $role;

        return $this;
    }

    /**
     * GET Profiles
     *
     * @return Profile[]
     */
    public function getProfiles(): ArrayCollection
    {
        return $this->profiles;
    }

    /**
     * SET Profiles
     *
     * @param Profile[] $profiles
     * @return ProfileAssociation
     */
    public function setProfiles(ArrayCollection $profiles): ProfileAssociation
    {
        $this->profiles = $profiles;
        return $this;
    }

    /**
     * @param Profile ...$profiles
     * @return ProfileAssociation
     */
    public function addProfiles(Profile ...$profiles): ProfileAssociation
    {
        foreach ($profiles as $profile) {
            $this->profiles->add($profile);
        }

        return $this;
    }

    /**
     * @param Profile ...$profiles
     * @return ProfileAssociation
     */
    public function removeProfiles(Profile ...$profiles): ProfileAssociation
    {
        foreach ($profiles as $profile) {
            $this->profiles->removeElement($profile);
        }

        return $this;
    }

    /**
     * @param bool $mapped
     * @return array
     */
    public function toArray($mapped = false)
    {
        return [
            'user' => $this->user->getId(),
            'application' => $this->application->getId(),
            'profile' => $this->profile,
            'role' => $this->role
        ];
    }

    /**
     * @param $data
     * @return AbstractEntity
     * @throws \Fei\Entity\Exception
     */
    public function hydrate($data)
    {
        return parent::hydrate($data); // TODO: Change the autogenerated stub
    }
}
